config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :chores do
    post '/:id/assignments', to: 'assignment#create'
    patch '/:id/assignments/:id', to: 'assignment#update'
  end

  resources :dashboard, only: :index, as: 'user_dashboard'
  resources :dashboard, only: :update, as: 'join_house'

  resources :households, only: %i[index new create show] do
    resources :chores, only: %i[new create show update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authenticate_user

  def current_user
    @current_user ||= GoogleUserFacade.user({roommate: session[:user].symbolize_keys}) if session[:user_id]
  end

  def authenticate_user
   redirect_to root_path if current_user.nil?
  end
end

app/controllers/chores/assignment_controller.rb
class Chores::AssignmentController < ApplicationController
  def create
    # @chore = ChoresFacade.find_and_create_chore(@chore_id)
    @chore = ChoresFacade.find_nested_chore(@chore_id)
    assignment_info = {
      assignment:
      {
        completed: false,
        roommate_id: current_user.id,
        chore_id: params[:id]
      } }
    
      user_info = {
        roommate: {
          incomplete_chores: [@chore]
        }
      }

    AssignmentService.create_assignment(assignment_info)
    TasksFacade.post_task(params[:chore_name], current_user) # add form to take in chore_name
    GoogleUserFacade.update_user(user_info)
    redirect_to household_chore_path(household_id: params[:household_id], id: params[:id])
  end

  private 
    def assignment_params
      params.permit(:completed, :roommate_id, :chore_id)
    end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  def new
    @household_id = params[:household_id]
  end

  def create
    chore_info = {
      chore:
      {
        household_id: params[:household_id],
        task_name: params[:task_name],
        description: params[:description],
        weight: params[:weight].to_i,
        frequency: params[:frequency].to_i,
        outdoor: params[:outdoor]
      }
    }

    if chore_info[:chore].has_value?(nil)
      flash[:error] = 'Error:  Chore Not Created.'
      redirect_to new_household_chore_path
    else
      chore = ChoresFacade.create_chore(chore_info)
      flash[:success] = 'Chore Created!'
      redirect_to household_chore_path(id: chore.id)
    end
  end

  def show
    chore_id = params[:id].to_i
    @chore = ChoresFacade.find_and_create_chore(chore_id)
    @house = HouseholdsFacade.get_weather(@chore.household_id)
    @daily_forecast = @house.weather_forecast[:daily_weather]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @incomplete_chores = @user.incomplete_chores
    @completed_chores = @user.completed_chores
  end

  def update
    update_info = {
      roommate: {
        id: params[:id],
        household_id: params[:household_id]
      }
    }
    # require 'pry'; binding.pry
    a = GoogleUserFacade.update_user(update_info)
    redirect_to user_dashboard_index_path
  end
end

app/controllers/households/chores_controller.rb
class Households::ChoresController < ApplicationController
  def new;  end

  def create
    # @household = Household.find(params[:household_id])
    chore_info = {
      chore:
      {
        household_id: params[:household_id],
        task_name: params[:task_name],
        description: params[:description],
        weight: params[:weight],
        frequency: params[:frequency],
        outdoor: params[:outdoor]
      }
    }

    ChoresFacade.create_chore(chore_info)
    flash[:success] = 'Chore Created!'
  end
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  # def index
  #   # redirect_to "/households/#{current_user.household_id}"
  # end

  def new; end

  def create

    household_info = {
      household:
      {
        address: params[:address],
        city: params[:city],
        state: params[:state],
        password: params[:password],
        password_confirmation: params[:password_confirmation]
      }
    }

    household = HouseholdsFacade.create_household(household_info)
    flash[:success] = 'House Created!'

    household_id = {
                    roommate:
                    {
                    household_id: household.id
                    }
                    }

    GoogleUserFacade.update_user(household_id)
    redirect_to household_path(id: household.id)
  end

  def show
    @user = current_user
# binding.pry
    # if current_user.household_id == params[:id].to_i
      @household = HouseholdsFacade.get_household_by_id(params[:id])

      room_mates = @household.roommates

      @roommates = room_mates.map do |roommate|
        info= GoogleUsersService.find_by_id(roommate[:id])
        formatted = info[:data][:attributes]
        GoogleUser.new(formatted)
      end
    # else
    #   redirect_to user_dashboard_index_url
    # end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user

  def create
    auth_hash = request.env['omniauth.auth']
    user_info = {
      roommate:
      {
        name: auth_hash['info']['name'],
        email: auth_hash['info']['email'],
        google_id: auth_hash['uid'],
        token: auth_hash['credentials']['token']
      }
    }

    user = GoogleUserFacade.user(user_info)

    session[:user_id] = user.google_id
    session[:user] = user
    if user.nil?
      flash[:error] = "Sorry, sign in not successful."
      redirect_to root_path
    else
      flash[:success] = "Welcome #{user.name}!"
      redirect_to user_dashboard_index_path
    end
  end

  def destroy
    session[:user] = nil
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/chores/new.html.erb
<%= render partial: 'partials/navbar' %><br>

<div class="container" style="width: 45%">
  <div class="col-sm", style='padding-left: 25px'>
    <br><h2>Create New Chore</h2>
    <section><hr><br>

      <div id='createChore' %>
        <%= bootstrap_form_with(model: @chore, url: household_chores_path, method: :post, local: true) do |f| %>
          <%= f.hidden_field :household_id, value: :household_id %><br>
          <%= f.text_field :task_name, placeholder: "Enter task name", skip_label: true %><br>
          <%= f.text_area :description, placeholder: "Enter description", skip_label: true %><br>
          <h5 class="left">Select Difficulty (below):</h5>&emsp;&emsp;<%= f.select :weight, [["Simple", 1], ["Medium", 2], ["Hard", 3]], skip_label: true %><br>
          <h5 class="left">Select How Often (below)::</h5>&emsp;&emsp;<%= f.select :frequency, [["Weekly", 1], ["Bi-Monthly", 2], ["Monthly", 3]], skip_label: true %><br>
          <h5 class="left"><span>&#10003; </span>Box if Outdoor</h5>&emsp;&emsp;<%= f.check_box :outdoor, skip_label: true %><br><br>
          <%= f.submit 'Submit Chore' %><br>
        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/chores/show.html.erb
<h1><%= @chore.task_name %></h1>

<%
=begin%>
 <%= form_with url: "/households/#{@house.id}/chores/#{@chore.id}", method: :patch, local: true do |form| %>
  <%= form.submit 'Update Chore' %>
<% end %> 
<%
=end%>

<% if !current_user.incomplete_chores.include?(@chore) %>
  <%= form_with url: "/chores/#{@chore.id}/assignments", method: :post, local: :true do |form| %>
    <%= form.hidden_field :household_id, :value => @chore.household_id %>
    <%= form.hidden_field :chore_name, :value => @chore.task_name %>
    <%= form.submit 'Claim Chore' %>
  <% end %>
<% end %>

<% if @chore.location == 'Outdoor' %>
  <h2>Weather Forecast</h2>
  <div class="card-group">
    <% @daily_forecast.each do |day| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= day[:date].to_datetime.strftime("%A") %></h5>
          <p>High: <%= day[:max_temp] %></p>
          <p>Low: <%= day[:min_temp] %></p>
          <p>Conditions</p>
          <p><%= day[:conditions] %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<ul>
  <li>Description: <%= @chore.description %></li>
  <li>Frequency: <%= @chore.frequency %></li>
  <li>Weight: <%= @chore.weight %></li>
  <li>Location: <%= @chore.location %></li>
</ul>

app/views/dashboard/index.html.erb
<%= render partial: 'partials/navbar' %><br><br>

<h1><%= current_user.name.split.first %>'s Dashboard</h1><hr>

<% if current_user.household_id.nil? %>
    <%
=begin%>
 <div class="left">
      <h5>&emsp;&emsp;&emsp;&emsp;<%= link_to "=> New Household Link", new_household_path %></h5><br><br>
    </div> 
<%
=end%>

    <div class='createHousehold' %>
      <%= bootstrap_form_with(url: households_path, method: :patch, class: 'form-inline', local: true) do |f|  %><h4 class="tab">Join a Household:</h4>&emsp;
        <%= f.text_field :household_id, placeholder: "Enter household ID", skip_label: true %><br>&emsp;&emsp;
        <%= f.submit 'Submit' %>
      <% end %> <br><br><br>

      <%= form_with url: join_house_path(id: current_user.id), method: :patch, remote: true do |form| %>
        <%= form.label :household_id, 'Enter Households id:' %>
        <%= form.text_field :household_id %>
        <%= form.submit 'Find and Join Household' %>
      <% end %>

      <br><br><p>Join or create a household</p>
<% else %>
  <ul class="incompleteChores" align-text='left'>
    <h2>Incomplete Chores</h2>
    <% if @incomplete_chores.nil? %>
      <p>You have no incomplete chores!🎉</p>
    <% else %>
      <% @incomplete_chores.each do |incomplete_chore| %>
        <li>Task Name: <%= link_to "#{incomplete_chore[:task_name]}", household_chore_path(incomplete_chore[:household_id], incomplete_chore[:id])%></li>
        <li>Description: <%= incomplete_chore[:description] %></li>
        <li>Frequency: <%= incomplete_chore[:frequency] %></li>
        <li>Weight: <%= incomplete_chore[:weight] %></li>
        <li>Location: <%= incomplete_chore[:location] %></li>
        <%
=begin%>
 <% if incomplete_chore.assignments.empty? %>
          <p>You have Assigments</p>
        <% else %>
          <li><%= button_to "Done", "/chores/#{incomplete_chore[:id]}/assignments/#{incomplete_chore.assignments[-1][:id]}", method: :update %></li>
        <% end %> 
<%
=end%>
      <% end %>
    <% end %>
  </ul>

  <ul class="completedChores">
    <h2>Complete Chores</h2>
    <% if @completed_chores.nil? %>
      <p>You have no completed chores😭.</p>
    <% else %>
      <% @completed_chores.each do |completed_chore| %>
        <li>Task Name: <%= link_to "#{completed_chore[:task_name]}", household_chore_path(completed_chore[:household_id], completed_chore[:id])%></li>
        <li>Description: <%= completed_chore[:description] %></li>
        <li>Frequency: <%= completed_chore[:frequency] %></li>
        <li>Weight: <%= completed_chore[:weight] %></li>
        <li>Location: <%= completed_chore[:location] %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>
<br><br><br><br>
<%= button_to "Log out", '/logout', method: :delete %>

app/views/households/new.html.erb
<%= render partial: 'partials/navbar' %><br><br>

<h1>Create New Household</h1><hr>
<br>
<h3>Please create or Join a household</h3><br>

<section>
  <div class='createHousehold' %>
    <%= bootstrap_form_with(url: households_path, method: :post, class: 'form-inline', local: true) do |f|  %><h4 class="left">Location:</h4>&emsp;
      <%= f.text_field :address, placeholder: "Enter address", skip_label: true %><br>&emsp;
      <%= f.text_field :city, placeholder: "Enter city", skip_label: true %><br>&emsp;
      <%= f.text_field :state, placeholder: "Enter state", skip_label: true %><br><br>
      <h4 class="left">Password:</h4>&emsp;<%= f.text_field :password, placeholder: "Enter password", skip_label: true %><br>&emsp;
      <%= f.text_field :password_confirmation, placeholder: "Confirm password", skip_label: true %><br>&emsp;&emsp;&emsp;
      <%= f.submit 'Create Household' %>
    <% end %> <br><br><br>

  <%= form_with url: households_path, method: :post, local: true do |form| %>
    <%= form.label :address, 'Address' %>
    <%= form.text_field :address, required: :true %>
    <%= form.label :city, 'City' %>
    <%= form.text_field :city, required: :true %>
    <%= form.label :state, 'State' %>
    <%= form.text_field :state, required: :true %>
    <%= form.label :password, 'Password' %>
    <%= form.text_field :password, required: :true %>
    <%= form.label :password_confirmation, 'Confirm Your Password' %>
    <%= form.text_field :password_confirmation, required: :true %>
    <%= form.submit 'Submit' %>
  <% end %>
  </div>
</section>

app/views/households/show.html.erb
<%= render partial: 'partials/navbar' %><br><br>

<%= "#{@household.weather_forecast[:current_weather][:conditions]}"%>
<br>
<%= "Welcome to Household #{@household.id}" %><br><br>


<%= "Roommates" %><br>

<% @roommates.each  do |roommate|%>
<br>
  <%=  roommate.name %> <br>
  <% total_points = 0  %>
  <% roommate.completed_chores.each do |chore| %>
    <%= link_to "#{chore[:task_name]}", "#{@household.id}/chores/#{chore[:id]}", method: :get %><br>
    <% total_points +=  chore[:weight]  %>
  <% end %>
  <% roommate.incomplete_chores.each do |chore| %>
    <%= link_to "#{chore[:task_name]}", "#{@household.id}/chores/#{chore[:id]}", method: :get %><br>
    <% end %>
  <%= "total points #{total_points}" %><br>
<% end %>

<br>
<br>

<%= "list all chores" %><br>
<% @household.chores.each  do |chore|%>
<%= link_to "#{chore[:task_name]}", "#{@household.id}/chores/#{chore[:id]}", method: :get %>
  <%= chore[:weight] %><br>
<% end %>

<br>
<br>

<%= "list unassigned chores" %><br>
<% @household.chores.each  do |chore|%>
<%= link_to "#{chore[:task_name]}", "#{@household.id}/chores/#{chore[:id]}", method: :get %>
  <% chore[:weight] %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Choreganize</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <main>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %><br><br>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>

  <h2 class='navbar-brand'></h2>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <h4><%= link_to 'My Dashboard', user_dashboard_index_path, class:'badge badge-light' %>&ensp;</h4>
      </li>
     <li class="nav-item">
        <% if current_user.household_id.nil? %>
          <h4><%= link_to "Create A Household", new_household_path, class:'badge badge-light' %></h4>
        <% else %>
          <h4><%= link_to 'My Household', household_path(id: current_user.household_id), class:'badge badge-light' %></h4>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<div
  class="p-5 text-center bg-image"
  style="
    background-image: url('https://image.freepik.com/free-photo/neat-desktop-with-office-appliances_23-2147833239.jpg');
    height: 175px;
  "
>
  <div class="mask" >
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-green">
        <br><br><br>
        <h1 class="mb-3">CHOREganize</h1>
        <br><p> Organizing is no longer a chore with the Choreganize app. <br> Create
        your household, invite roommates, add & claim chores.  Done!
        </p>

        <br><br><br><br><br><br>
        <%= button_to 'Sign in with Google', '/auth/google_oauth2', method: :get %><br><br>
      </div>
    </div>
  </div>
</div>